export const CONFIG = {
  TRANSACTION_INPUT_CSV_FILENAME: 'data/transactions-input.csv',
  REPORT_MARKDOWN_FILENAME: 'data/report.md',
  PRIORITIES_RANKED: [
    'Work',
    'Need',
    'Fitness',
    'Family',
    'Personal Growth',
    'BU Friends',
    'Morgan',
    'Boston Friends',
    'HS Friends',
    'Snowboarding',
    'Savings',
    'Health',
    'Self Indulgence',
    'Credit Card Points',
  ],
}
